### ISSUE TITLE
What is the recommended way to create OS level user?

### ISSUE THREAD

**Issue by tkang007** [jupyterhub/ldapauthenticator#109]
Hi,

Thanks for your very nice package!

As my testing, OS level user should be prepared before using LDAP/AD authentication.

Do you have any recommended way to create OS level user before using LDAP/AD auth?  

With home directory creation option, it always failed if the user was not in the OS level.  

When add a user at JupyterHub admin user,  can we create OS user and/or  Home directory ?

If we have any way to create a user with proper UID/GID based on LDAP/AD attributes,
it might be perfect for various use cases, such as multiple nodes shared file system.  

Unfortunately, I cannot use OS level LDAP/AD integration as limited privileges for LDAP/AD domain join.

Thanks,
Taewon

**Comment by manics** [comment]
I think https://github.com/jupyterhub/ldapauthenticator/issues/19 will have a solution.
