### ISSUE TITLE
Accessing additional information of the authenticated user (e.g. memberOf, OU the user is in)

### ISSUE THREAD

**Issue by krassers** [jupyterhub/ldapauthenticator#112]
Hi,

In our university we're on our way to create a Kubernetes cluster with a JupyterHub deployment for data science students. Our current setup consists of a zero-to-jupyterhub deployment which is deployed with Helm.
We are using the LDAPAuthenticator for authentication through Active Directory. The problem we are facing is that we have different cohortes which need different Jupyter Notebooks. We want to accomplish this by using the OU the user belongs to in LDAP. 
The bind template of the authenticator looks something like this: `CN={username}, OU=IMA16`, some more OUs...

So in this case we would like to access the `OU=IMA16` of the authenticated user to decide based on the content which image to start. 

Unfortunately, the `authenticate()` function only returns the username which is why we are somehow stuck and could need some help.

Thank you!

**Comment by manics** [comment]
This should be in the forthcoming release https://github.com/jupyterhub/ldapauthenticator/pull/103
