### ISSUE TITLE
Why ldapauthenticator is not creating user in centos at the time of authentication.

### ISSUE THREAD

**Issue by II-VSB-II** [jupyterhub/ldapauthenticator#113]
Hi All, I configure the LdapAuthentication with jupyterhub but I need to add user manually to centos then only its working if there is no user in centos with uid then it throwing an error.
Is there any flag we need to set to jupyterhub config to create the user automatically in centos at the time of jupyterhub login. Please let me know.

Thanks in advance. !

**Comment by II-VSB-II** [comment]
@yuvipanda @minrk Jupyterhub is running fine while login first time but when try to login with another user its failing.

**Comment by SahithiGunna** [comment]
I have a similar issue as well and trying to find the solution. Did anyone respond to you personally regarding the fix?

**Comment by alexmorley** [comment]
Hi @II-VSB-II and @SahithiGunna as far as I understand this is not currently supported in LDAPAuthenticator by default due to security issues. There is an in depth discussion (as well as several work arounds) in this thread: https://github.com/jupyterhub/ldapauthenticator/issues/19

**Comment by manics** [comment]
Thanks for linking to that issue. Since this issue has been open a year and it sounds like there's a workaround I'm going to close this.
