### ISSUE TITLE
AD configuration, need help it was replying invalid user name and password

### ISSUE THREAD

**Issue by mannevijayakrishna** [jupyterhub/ldapauthenticator#115]
i hae give a multiple ways to configure but i am still getting the responce is invalid username and passwd can some one please help me.

os: redhat 
APP: jupyter hub
LDAP : AD(active directory 

responce :   
![jupyterhub ad](https://user-images.githubusercontent.com/37191587/51861018-27262580-2309-11e9-8306-18f26e1e6435.PNG)

``
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'AD ip address'
c.LDAPAuthenticator.server_port = 389

c.MyAuthenticator.bind_dn_template = ['cn={username},dc=example ,dc=local']

c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = 'dc=example,dc=local'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_search_user = 'LDAP@example.local'
c.LDAPAuthenticator.lookup_dn_search_password = '*****************'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'
c.LDAPAuthenticator.use_ssl = False
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.escape_userdn = False
#c.LDAPAuthenticator.valid_username_regex = '^[A-Za-z][.A-Za-z0-9_-]*$'

**Comment by dhirschfeld** [comment]
Try running `jupyterhub` with the `--debug` flag and then post the log output after a failed login attempt

**Comment by xmatthias** [comment]
in my environment (also AD) i need to specify the search-user based on DN as follows, and i think you'll need to do the same to get it to work:

```
c.LDAPAuthenticator.lookup_dn_search_user = 'CN=ADHelperRO,OU=Users,DC=example,dc=local'
```

**Comment by mannevijayakrishna** [comment]
> Try running `jupyterhub` with the `--debug` flag and then post the log output after a failed login attempt

right now I am running with --debug. still geting same error : 

`[W 2019-01-29 09:03:55.620 JupyterHub ldapauthenticator:379] Invalid password for user krishna1
[W 2019-01-29 09:03:55.621 JupyterHub base:504] Failed login for krishna1
[I 2019-01-29 09:03:55.643 JupyterHub log:158] 200 POST /hub/login?next= (@127.0.0.1) 292.09ms`

**Comment by mannevijayakrishna** [comment]
please help this issues is still not resolved 
`[W 2019-02-05 13:04:21.859 JupyterHub ldapauthenticator:242] username:abcd123 No such user entry found when looking up with attribute sAMAccountName
`

but this user exists in AD. I am able to see the ldapsearch and looking at everything is fine but jupyter is not able to recognize the user by using LDAP.

`[D 2019-02-05 13:04:21.561 JupyterHub ldapauthenticator:223] Looking up user with search_base=ou=personCN=ABC Team,OU=Distribution Groups,OU=Groups,dc=example,dc=com, search_filter='(&(|(mail=*)(proxyAddresses=*))(sAMAccountName=*))', attributes=sAMAccountName
[W 2019-02-05 13:04:21.859 JupyterHub ldapauthenticator:242] username:abcd123 No such user entry found when looking up with attribute sAMAccountName
[W 2019-02-05 13:04:21.859 JupyterHub base:504] Failed login for abcd123
`

**Comment by xmatthias** [comment]
`search_base=ou=personCN=ABC Team,OU=Distribution Groups,OU=Groups,dc=example,dc=com`
is this a typo from anonymizing or do you really miss the comma between `ou=person` and `CN`

**Comment by mannevijayakrishna** [comment]
this issue was resolved. thank you very much for your help!!

**Comment by xmatthias** [comment]
what was the problem (if you don't mind sharing) - that would help others resolve the problem as well...

**Comment by mannevijayakrishna** [comment]
it was just configuration error on 

c.**LDAP**Authenticator.lookup_dn_search_user = [' <user base DN>']

**Comment by marcreyesph** [comment]
Hi @mannevijayakrishna what value did you use for `c.LDAPAuthenticator.lookup_dn_search_user = [' ']`?

**Comment by xmatthias** [comment]
well, for me it's `c.LDAPAuthenticator.lookup_dn_search_user = os.environ["LDAP_USER"]` ...

I'm in a Windows AD Environment, so LDAP_USER is set to the CN (e.g. `LDAP_USER=CN=JupyterHelper,DC=contoso,DC=com`

Obviously, you also need to set `c.LDAPAuthenticator.lookup_dn_search_password = os.environ["LDAP_PASSWORD"]`- to the corresponding password of that user.
