### ISSUE TITLE
Authenticator class cannot be imported

### ISSUE THREAD

**Issue by vishma** [jupyterhub/ldapauthenticator#123]
I have tried to use ldap authenticator with jupyterhub 0.9.6. 

I have added this to my jupyterhub config file.

c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'

I am getting the following error. However I can import LDAPAuthenticator class from a python script therefore I assume ldapauthenticator has installed correctly.

Any help would be appreciated. 
Thanks !!! 

< ERROR MESSAGE>

[C 2019-05-16 15:13:10.140 JupyterHub application:90] Bad config encountered during initialization:
[C 2019-05-16 15:13:10.140 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7fb07ce86d68> instance must be a type, but 'ldapauthenticator.LDAPAuthenticator' could not be imported

**Comment by dhirschfeld** [comment]
Sounds like you're running jupyterhub from a different python environment than the one you tested in. ldapauthenticator will have to be installed in the environment which jupyterhub runs in

**Comment by vishma** [comment]
You are correct. Turns out when I use sudo jupyterhub cmd to start the server it uses the system-wide default python installation instead of my conda virtual environment. 

Thanks for the reply.

**Comment by vishma** [comment]
You are correct. Turns out when I use sudo jupyterhub cmd to start the server it uses the system-wide default python installation instead of my conda virtual environment. 

Thanks for the reply.
