### ISSUE TITLE
How to pass domain/username through LDAP

### ISSUE THREAD

**Issue by jljs** [jupyterhub/ldapauthenticator#125]
Hi,

I am trying to setup JupyterHub with Active Directory. I am getting the following error when authenticating users

LDAPBindError: automatic bind not successful - invalidCredentials

I am suspecting that this is due to my company's ldap server require to pass domain\username at the same time. I am just wondering how to set this up in jupyterhub_config.py

Thanks

Jeffrey

**Comment by consideRatio** [comment]
I think this could have been the result of an incorrect docs example which is now fixed thanks to investigative effort in https://github.com/jupyterhub/ldapauthenticator/issues/199
