### ISSUE TITLE
Jupyterhub Active Directory Authentication

### ISSUE THREAD

**Issue by JulianTBZ** [jupyterhub/ldapauthenticator#129]
Hi all, 
I have a problem with the authentication against the Active Directory. 
I read the other posts but none of them could solve my problem. 

This is my jupyterhub_config.py

```python
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_hosts = ['192.168.x.x']
c.LDAPAuthenticator.server_address = '192.168.x.x'
c.LDAPAuthenticator.bind_user_dn = 'CN=qeryuser,CN=users,DC=example,DC=com'
c.LDAPAuthenticator.bind_user_password = 'SecurePassword'
c.LDAPAuthenticator.user_search_filter = '(&(objectCategory=person)(objectClass=user)(userPrincipalName={username}))'
c.LDAPAuthenticator.bind_dn_template = 'example.com{username}'
c.LDAPAuthenticator.lookup_dn = False
c.LDAPAuthenticator.user_search_base = 'OU=ADUsers,DC=example,DC=com'
c.LDAPAuthenticator.user_attribute = 'userPrincipalName'
c.LDAPAuthenticator.allowed_groups = ['CN=Domain Users,CN=Users,DC=example,DC=com']
c.LDAPAuthenticator.allow_nested_groups = True
c.LDAPAuthenticator.username_pattern = '[a-zA-Z0-9_.][a-zA-Z0-9_.-]{8,20}[a-zA-Z0-9_.$-]?'
c.LDAPAuthenticator.create_user_home_dir = True
c.LDAPAuthenticator.create_user_home_dir_cmd = ['mkhomedir_helper']
```

If I use a User that doesn't exist in the AD I get the following message. 
```
LDAP search '(&(objectCategory=person)(objectClass=user)(userPrincipalName=user9))' found 0 result(s).
```
So I guess the user query works. 

But if I take any user from the AD I can type anything for the password and I get the 
```
500 : Internal Server Error
````
so I think no password check is made. 
The log file gives out the following error. 
```
Uncaught exception POST /hub/login?next= (::ffff:192.168..x)
    HTTPServerRequest(protocol='http', host='example.com:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:192.168.x.x')
    Traceback (most recent call last):
```
Does someone knows how to fix this error?
Thanks
KR

**Comment by dhirschfeld** [comment]
The text which follows after
```
Traceback (most recent call last): 
```

...contains the actual traceback which would enable someone to potentially help diagnose the issue.

**Comment by JulianTBZ** [comment]
Ok.
This is the following text: 

`Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 559, in authenticate
        nested_groups = self.get_nested_groups(conn, group)
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 399, in get_nested_groups
        search_scope=ldap3.SUBTREE)
      File "/usr/local/lib/python3.6/dist-packages/ldap3/core/connection.py", line 779, in search
        check_names=self.check_names)
      File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 372, in search_operation
        request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
      File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 220, in parse_filter
        raise LDAPInvalidFilterError('invalid filter')
    ldap3.core.exceptions.LDAPInvalidFilterError: invalid filter`

**Comment by JulianTBZ** [comment]
Hi, I could fix the problem by binding the Server to the Active Directory DC. 
So the login is now successful. 
But after processing the user's login I just get redirected to the login page. 
In the log, everything seems okay to me. 

<img width="1425" alt="Bildschirmfoto 2019-07-19 um 11 52 35" src="https://user-images.githubusercontent.com/36665360/61527209-31a1bc00-aa1c-11e9-9318-26e6e17ae085.png">
The home also exists in the /home/ directory. 

Is it a problem, that the home folder is called vorna.nachname and the username is vorname.nachname@domain.com?

Thanks for any help. 
KR,
Julian

**Comment by kinow** [comment]
I think that might be the problem Julian. In my case I was getting an error due to this line

![image](https://user-images.githubusercontent.com/304786/86983866-1b6aae00-c1e1-11ea-912f-113a1c71eaf6.png)

Once I changed my settings to use `c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'samaccountname'` (samaccountname is the value that I needed for `/home/$samaccountname`) I could authenticate and the process was spawned correctly by JHub.
