### ISSUE TITLE
Is there a reason for resolve_username not being resolve_userdn ?

### ISSUE THREAD

**Issue by roman-kouzmenko** [jupyterhub/ldapauthenticator#131]
In my case, the active directory DNs include the office name, so that the bind_dn_template template varies both by user name and by user location (perhaps not the best practice but I have no control over it).

Is there a reason why instead of resolving the user name when lookup_dn is set to True, we don't resolve the full DN (as the parameter name says) instead of just finding an alternative user name and plugging it into a DN template? It seems it would make the system more generic.

It could then be used both to authenticate and to check group membership if required.

Thanks!

**Comment by beenje** [comment]
I have the exact same question.
I couldn't make this version work with our AD at work. I created a fork a while ago: https://github.com/beenje/ldapauthenticator/commit/0c0583e6be83d3cc39fd81e1f67053a3eda2f77b

When `lookup_dn` is set to True, this forks retrieves directly the full DN. It's working fine for us.

I'll be happy to create a PR if this is of interest.

**Comment by beenje** [comment]
I just saw there is actually already a PR with a similar change: https://github.com/jupyterhub/ldapauthenticator/pull/106
