### ISSUE TITLE
PYPI

### ISSUE THREAD

**Issue by pbecotte** [jupyterhub/ldapauthenticator#138]
Spent some time today wandering down rabbitholes getting this to work on my new k8s jupyterhub deployment. In the process, was very confused that the github repo of the package installed in their image doesn't come from this repo. It looks like it may have been moved at some point, but there has never been a release with the new metadata (or the last years worth of commits). Is there a way to make that happen?

**Comment by consideRatio** [comment]
I know that the current master of z2jh has the latest release on PyPI installed, see: https://jupyterhub.github.io/helm-chart/ for the dev-version of the latest z2jh chart.
