### ISSUE TITLE
Fail to resolve name

### ISSUE THREAD

**Issue by jmercier-lbi** [jupyterhub/ldapauthenticator#141]
Dear,
I got a but at line [308](https://github.com/jupyterhub/ldapauthenticator/blob/1.2.2/ldapauthenticator/ldapauthenticator.py#L308)

in my case the var `resolved_username` is an array of 1 item while the code expects to get a string

so I suggest fixing the code like this:

```python
if isinstance(resolved_username, typing.List) or isinstance(resolved_username, typing.Tuple):
  resolved_username = resolved_username[0]
resolved_username = re.subn(r"([^\\]),", r"\1\,", resolved_username)[0]
```

**Comment by consideRatio** [comment]
I think this is fixed already via #117
