### ISSUE TITLE
The lookup takes your samid which you use to login with and looks up your CN (`lookup_dn_user_dn_attribute`).

### ISSUE THREAD

**Issue by tyu0912** [jupyterhub/ldapauthenticator#143]
The lookup takes your samid which you use to login with and looks up your CN (`lookup_dn_user_dn_attribute`).

e.g. My DN might be something like `CN=Dave Hirschfeld,OU=People,OU=Company,OU=com` but my login username (samid) is `dhirschfeld`. In this case your `bind_dn_template` would be
```
'CN={username},OU=People,DC=Company,DC=com'
```
where `username` would be populated with the result of looking up the CN for `dhirschfeld`

_Originally posted by @dhirschfeld in https://github.com/jupyterhub/ldapauthenticator/issues/98#issuecomment-411356276_

**Comment by tyu0912** [comment]
Hello, I'm not sure if this is the right spot to post but I have been banging my head with configuring jupyterhub and ldap. I think my issue is related to the above. Firstly, I keep getting the first error below. It seems the {username} variable is not passed from the login page. When I hardcode my username, it gives me the second error. Does anyone know how to address this? Also my config is below. Would really appreciate any help on this. Thanks!

` Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 483, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/conda/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 301, in authenticate
        resolved_username = self.resolve_username(username)
      File "/opt/conda/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 237, in resolve_username
        attributes=[self.lookup_dn_user_dn_attribute]
      File "/opt/conda/lib/python3.6/site-packages/ldap3/core/connection.py", line 766, in search
        if ';' in attribute_name:  # remove tags
    TypeError: argument of type 'NoneType' is not iterable`

**Comment by dhirschfeld** [comment]
You need to show your full config (redacting any sensitive info)  if you want anyone to be able to help you

**Comment by tyu0912** [comment]
Hi @dhirschfeld, apologies again, was trying to reproduce part of my troubles above. Any advice would be awesome.

**Comment by dhirschfeld** [comment]
Since your `dn` has  `uid` it looks like you're using OpenLDAP in which case you need to specify that as the [`user_attribute`](https://github.com/jupyterhub/ldapauthenticator#ldapauthenticatoruser_attribute). MAybe try the below:
```
c.LDAPAuthenticator.user_attribute = 'uid'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'uid'
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
```

**Comment by tyu0912** [comment]
Cool. The username seems to be pulling now. Not sure why but so happy to get over this hurdle! Though, I seem to have a new problem now... I'm now getting `[W 2019-10-25 06:20:42.743 JupyterHub ldapauthenticator:230] Can't connect to LDAP` error which is strange since I can do ldapsearch for the info.. I also just checked my authenticator packages and they seem up to date. No updates on pip+git installing, etc. Would you happen to know what the best approach is here? 
`

**Comment by dhirschfeld** [comment]
No idea sorry - I think your best bet to debug it is to pass your config directly to the unerlying `ldap3` library as shown in https://github.com/jupyterhub/ldapauthenticator/issues/116#issue-407542672

You're likely to get better error messages when using the underlying library directly.

**Comment by tyu0912** [comment]
That's very useful. Thank-you. Will give it a shot. I do have one more sort of side question if you're willing (no worries if not). Part of the process I am following is from the aws instructions here: https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-jupyterhub-ldap-users.html but one thing I am really confused about is what role the `ldap.conf` file has with all of this...
