### ISSUE TITLE
How to address ldapauthenticator:379 - Invalid password for user?

### ISSUE THREAD

**Issue by tyu0912** [jupyterhub/ldapauthenticator#144]
Hello, I'm getting the above error and not sure what the best way to troubleshoot is. I was getting another error before and managed to work through that here with some help: https://github.com/jupyterhub/ldapauthenticator/issues/143 . Any idea how to approach? I'm sort of eyeing `c.LDAPAuthenticator.lookup_dn_search_filter` since I am unfamiliar what those variables reference and how the final output will be. I tested filtering on a separate py file using ldap3 using `search_filter='(uid=<uid>)` attribute and it works. Thanks! Appreciate any insight. 

```
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'myAddress'
c.LDAPAuthenticator.bind_dn_template = 'uid={username},ou=<ou>,o=<o>,dc=example,dc=com'
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = 'ou=<ou>,o=<o>,dc=example,dc=com'
c.LDAPAuthenticator.lookup_dn_search_user='uid=<manager_uid>,ou=<ou>,o=<o>,dc=example,dc=com'
c.LDAPAuthenticator.lookup_dn_search_password=<passwd>
c.LDAPAuthenticator.user_attribute = 'uid'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'uid'
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
```

**Comment by consideRatio** [comment]
I think maybe this could be fixed by removing bind_dn_template config, but I'm not sure. This is discussed via https://github.com/jupyterhub/ldapauthenticator/issues/199. At this point I'll go for a close as its a very old issue.
