### ISSUE TITLE
Group access inheritance issue

### ISSUE THREAD

**Issue by leetim** [jupyterhub/ldapauthenticator#148]
Access inheritance does not work. For example, group A contains group B, that is, the rights that apply to group A should also apply to group B. But in fact, only users of group A directly receive these rights.

**Comment by Aethylred** [comment]
Does this solution also provide support for nested groups from FreeIPA/RedHat Identity Manager? (a.k.a. 389 Directory Server)?

**Comment by consideRatio** [comment]
Closing in favor of duplicated #177 that provided some more context.
