### ISSUE TITLE
TLJH LDAPAuthenticator Creating Local User Accounts

### ISSUE THREAD

**Issue by haloforensics** [jupyterhub/ldapauthenticator#149]
So I installed TLJH on my own server (ubuntu 18.04) and have just installed the ldapauthenticator.  The LDAP/Active Directory authentication appears to be working correctly, however upon logging in, a user account is being created on the server for each user (jupyter-[username]).  I see these accounts when running "cat /etc/passwd".  Based on the readme, I did not expect this to happen. 

My TLJH config.yaml file is as follows:

users:
  admin:
      user
https:
  enabled: true
  tls:
    key: /etc/certs/domain.key
    cert: /etc/certs/domain.crt
user_environment:
  default_app: jupyterlab
auth:
  type: ldapauthenticator.LDAPAuthenticator
  LDAPAuthenticator:
    server_address: ###.###.###.###
    lookup_dn: true
    lookup_dn_search_filter: '({login_attr}={login})'
    lookup_dn_search_user: 'CN=[user],OU=[disto_group],OU=[disto_group],OU=[disto_group],DC=[domain],DC=[tld]'
    lookup_dn_search_password: '[password]'
    lookup_dn_user_dn_attribute: 'cn'
    user_search_base: 'ou=[disto_group],dc=[domain],dc=[tld]'
    user_attribute: 'sAMAccountName'
    escape_userdn: false
    server_port: 389
    bind_dn_template: 'CN=[user],OU=[disto_group],OU=[disto_group],OU=[disto_group],DC=[domain],DC=[tld]'
    valid_username_regex: ^[a-zA-Z][.a-z0-9_-]*$
  log_level: DEBUG

I know the LDAP authenticator is working since I can authenticate with my legitimate credentials.  Likewise, when I test non-legitimate credentials, I see the following entry in the log file using "jounralctl -u jupyterhub"

[JupyteHub ldapauthenticator:242] username:fail_test No such user entry found when looking up with attribute sAMAccountName

[JupyterHub base:670] Failed login for fail_test

My conda environment is: 

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
alembic                   1.3.2                      py_0    conda-forge
asn1crypto                1.2.0                    py36_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.13.2           py36h8022711_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
conda                     4.8.0                    py36_1    conda-forge
conda-env                 2.6.0                h36134e3_1
conda-package-handling    1.6.0            py36h516909a_1    conda-forge
configurable-http-proxy   1.3.0                         0    conda-forge
cryptography              2.8              py36h72c5cf5_1    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
importlib_metadata        1.3.0                    py36_0    conda-forge
ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
ipython                   7.10.2           py36h5ca1d4c_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                    pypi_0    pypi
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py36_0    conda-forge
jupyter-client            5.3.4                    pypi_0    pypi
jupyter_client            5.3.3                    py36_1    conda-forge
jupyter_core              4.6.1                    py36_0    conda-forge
jupyterhub                1.0.0                    py36_0    conda-forge
jupyterhub-ldapauthenticator 1.2.2                   py_1000    conda-forge
jupyterlab                0.35.4                   pypi_0    pypi
jupyterlab-server         0.2.0                    pypi_0    pypi
jupyterlab_server         1.0.6                      py_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ldap3                     2.6.1                      py_0    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libuv                     1.33.1               h516909a_0    conda-forge
mako                      1.1.0                      py_0    conda-forge
markupsafe                1.1.1            py36h516909a_0    conda-forge
mistune                   0.8.4           py36h516909a_1000    conda-forge
more-itertools            8.0.2                      py_0    conda-forge
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  4.4.0                    pypi_0    pypi
nbgitpuller               0.6.1                    pypi_0    pypi
nbresuse                  0.3.0                    pypi_0    pypi
ncurses                   6.1                  hfc679d8_2    conda-forge
nodejs                    13.0.0               h10a4023_1    conda-forge
notebook                  5.7.8                    pypi_0    pypi
nteract-on-jupyter        2.0.7                    pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1d               h516909a_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandoc                    2.9                           0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.5.2                      py_0    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                    pypi_0    pypi
pip                       19.3.1                   py36_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.2                      py_0    conda-forge
psutil                    5.6.7                    pypi_0    pypi
ptyprocess                0.6.0                   py_1001    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pycosat                   0.6.3           py36h516909a_1002    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pycurl                    7.43.0.3         py36h16ce93b_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyrsistent                0.15.6           py36h516909a_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.7             h381d211_1004    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                    pypi_0    pypi
pyzmq                     18.1.1                   pypi_0    pypi
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py36_1    conda-forge
ruamel_yaml               0.15.80         py36h516909a_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py36_0    conda-forge
six                       1.13.0                   py36_0    conda-forge
sqlalchemy                1.3.12           py36h516909a_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   5.1.1                    pypi_0    pypi
tqdm                      4.40.2                     py_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.6                   py36_0    conda-forge
widgetsnbextension        3.4.2                    pypi_0    pypi
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

I would prefer that local user accounts not be created on the server, so any guidance anyone can provide regarding the account creations and preventing it from happening would be greatly appreciated.

**Comment by manics** [comment]
The automatic user creation is a feature of TLJH: https://the-littlest-jupyterhub.readthedocs.io/en/latest/topic/security.html

This authenticator doesn't create accounts. If you don't want users to have a local system account TLJH is probably not a good solution, instead you could look at setting up JupyterHub with [DockerSpawner](https://github.com/jupyterhub/dockerspawner) or on [Kubernetes](https://zero-to-jupyterhub.readthedocs.io/)

**Comment by haloforensics** [comment]
I see, thank you for the info.
