### ISSUE TITLE
CI/CD setup - PyPI Deployment token + conda feedstock info

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ldapauthenticator#150]
I'll put in work to refresh the CI/CD pipeline for this repo. @yuvipanda / @minrk, could you either make me a PyPI project maintainer or create a PyPI deploy token for this repo that you add to TravisCI as an environment variable named PYPI_PASSWORD ?

- Create PyPI deploy token scoped for this project only: https://pypi.org/manage/account/token/
- TravisCI settings, add PYPI_PASSWORD env var (all branches - required for use with tags): https://travis-ci.org/jupyterhub/ldapauthenticator/settings

---

I found the conda feedstock at https://github.com/conda-forge/jupyterhub-ldapauthenticator-feedstock. [I found some lines of code indicating that](https://github.com/conda-forge/jupyterhub-ldapauthenticator-feedstock/blob/b3cc202aa49c4dcc08a26bd6c693573841521066/recipe/meta.yaml#L41-L44) @dhirschfeld and @minrk are the only ones able to update the conda package following a PyPI release. I've never worked with a conda-feedstock, but would be happy to press merge on an automated pr coming there following a PyPI release.

**Comment by dhirschfeld** [comment]
Thanks @consideRatio  - since I have no time to maintain this repo properly I'm happy for you to step up!

**Comment by consideRatio** [comment]
@dhirschfeld I sadly cannot take on much in this repo except the more general simpler things. For example I figured I'd make sure to reduce future maintenance when it comes to making releases by setting up CD to PyPI.

**Comment by consideRatio** [comment]
Seems resolved mostly
