### ISSUE TITLE
specifiy admin user via ldap

### ISSUE THREAD

**Issue by seal61** [jupyterhub/ldapauthenticator#160]
Hey,

I have not found a way to grant administrator rights to a user who has logged in via LDAP. 
Is this possibility available, if so, where? 

Currently I cannot use the local administrator account, because the login mask only refers to LDAP accounts. For this I would first have to deactivate the plugin again. 

I would be glad about any information - thanks in advance!

**Comment by manics** [comment]
Does setting [`admin_users`](https://jupyterhub.readthedocs.io/en/stable/getting-started/authenticators-users-basics.html#configure-admins-admin-users) work?

**Comment by dmpe** [comment]
No, it did not. I had to explicitly disable it because LDAP and Admin_users would not merge....

**Comment by jeanparker** [comment]
I was looking for a way to set the admin group for LDAP/Active Directory authentication.
Since switching to LDAP disabled my previous created admin user.

**Comment by GlennHD** [comment]
This shouldn't be too hard to do based on LDAP group.  But until then, just add the following line in your `jupyterhub_config.py` file.
```
c.Authenticator.admin_users = {'MY_LDAP_ADMIN_ACCOUNT'}
```

**Comment by seal61** [comment]
> ```
> c.LDAPAuthenticator.admin_users = {'username'}
> ```

great - this worked for me! 
can you also tell me on how to put multiple users there? Separating usernames via comma doesn't work:

```
c.LDAPAuthenticator.admin_users = {'username,anotheruser,anotheruser'}
```

**Comment by GlennHD** [comment]
@seal61 so close!!! Try this.
```
c.Authenticator.admin_users = {'user1', 'user2', 'user3'}
```

**Comment by Aethylred** [comment]
Previous comment worked for me... but...

How do we specify admin using an LDAP group?

...I suspect we need an equivalent to

```
c.PAMAuthenticator.admin_groups = {'wheel'}
```

**Comment by javad87** [comment]
> > ```
> > c.LDAPAuthenticator.admin_users = {'username'}
> > ```
> 
> great - this worked for me! can you also tell me on how to put multiple users there? Separating usernames via comma doesn't work:
> 
> ```
> c.LDAPAuthenticator.admin_users = {'username,anotheruser,anotheruser'}
> ```
> 
> This not a big issue, because I'm now able to access the admin GUI again and set more admins there if necessary. I just wonder where the permissions are set / saved - If I change something via GUI nothing seems to change in the jupyterhub_config.py

How can I define admin users list in config.yaml (or helm values) file for helm deployment?
I used following configuration and hub and all other pods are in running states but still can not see Admin pannel in Control pannel....

I am using latest version of jupyterhub...
Is there any workaround for that?
tnx in advance

**Comment by consideRatio** [comment]
We have `admin_users` and #239 tracks adding `admin_groups`, going for a close here.
