### ISSUE TITLE
Adjust ldapauthenticator to work with ldap3 v2.8

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/ldapauthenticator#174]
### Bug description

After updating ldap3 from 2.7 to 2.8, the login was failing. This has been discussed in https://github.com/jupyterhub/ldapauthenticator/issues/171 and led to https://github.com/jupyterhub/ldapauthenticator/pull/172 .
Discussing with the ldap3 library authors revealed that the library has been used in a wrong way all the time long, see https://github.com/cannatag/ldap3/issues/855#issuecomment-674766920.

#### Expected behaviour
It should not matter whether ldap3 version 2.7 or 2.8 is used since this was no real compability break, they only enforced what should have been the case all the time long (the author is saying so).

#### Actual behaviour
Currently we are bound to ldap version 2.7 due to the current implementation.

#### Suggestion for solution

I just took the code from https://github.com/cannatag/ldap3/issues/855#issuecomment-674766920 and twisted it around to make it first correct and second more pythonic. So I replaced the lines regarding `auto_bind` like this:

```python
auto_bind = (
    ldap3.AUTO_BIND_TLS_BEFORE_BIND if use_ssl else ldap3.AUTO_BIND_NO_TLS
)
```

**Comment by 1kastner** [comment]
The discussion with the author continues, see https://github.com/cannatag/ldap3/issues/855#issuecomment-674829644 .

**Comment by 1kastner** [comment]
The corresponding pull request is at https://github.com/jupyterhub/ldapauthenticator/pull/175

**Comment by soobidou** [comment]
FYI,
The ldap3==2.8 was changed overnight in an old version of jupyterhub-ldapauthenticator==1.2.2 breaking our CI as that version doesn't fit well with our ldaps. To fix, had to override the version 1.2.2 installs to 2.7

Why was there a breaking change introduced in old, pinned version? Isn't it the purpose of version pinning? Stability and reproducibility.

**Comment by 1kastner** [comment]
https://github.com/jupyterhub/ldapauthenticator/pull/175 is merged.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-0-11-1-ldap-not-working/7591/12
