### ISSUE TITLE
Error 500 if user has a space in "CN"

### ISSUE THREAD

**Issue by marcusmills** [jupyterhub/ldapauthenticator#189]
### Bug description

After configuring ldapauthenticator, users with spaces in the CN value, like "CN=John Smith" log in and receive an error.

_"500 : Internal Server Error
Error in Authenticator.pre_spawn_start: CalledProcessError Command '['useradd', '--create-home', 'jupyter-john smith-eccf8']' returned non-zero exit status 3.

You can try restarting your server from the home page."_
#### Expected behaviour

Login in and home folder created and kernel started

#### Actual behaviour

Error creating home folder and linux user is not created. User is created in Jupyter Hub but cant do very much

### How to reproduce

Configure Jupyter Hub with the following ldap authentication options and use a user with a space in their CN.

```
c.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = 'contoso.com'
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = '<snip>'
c.LDAPAuthenticator.lookup_dn_search_password = '<snip>'
c.LDAPAuthenticator.user_search_base = 'OU=users,DC=contoso,DC=com'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'
c.LDAPAuthenticator.escape_userdn = True
c.LDAPAuthenticator.bind_dn_template = '{username}'
c.LDAPAuthenticator.use_lookup_dn_username = True

```

### Your personal set up

Using TLJH

 - OS:
 
 - Version(s): lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem,  `pre_spawn_start` isn't the responsibility of LdapAuthenticator. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? When you do so please include full details of your configuration and setup. Thanks!
