### ISSUE TITLE
AD Integration: No entry found for user when looking up attribute 'sAMAccountName'

### ISSUE THREAD

**Issue by yash64** [jupyterhub/ldapauthenticator#195]
I am facing issue in configuring ldap authentication with AD integration and I get error while logging in. Below is my config file.

```
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'

c.LDAPAuthenticator.server_address = '<ip>'
c.LDAPAuthenticator.server_port = 389
c.LDAPAuthenticator.use_ssl = False
c.LDAPAuthenticator.allowed_groups = []

#set up the template which used to bind the user from ldap directory
#c.LDAPAuthenticator.bind_dn_template = ["uid={username},ou=Admin,ou=Groups,dc=example,dc=com"]

#Active Directory Integration
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = 'user@example.com'
c.LDAPAuthenticator.lookup_dn_search_password = 'redact'
c.LDAPAuthenticator.user_search_base = 'ou=Admin,ou=Groups,dc=example,dc=com'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'
c.LDAPAuthenticator.escape_userdn = False
c.LDAPAuthenticator.bind_dn_template = '{username}'
```
While logging to jupyterhub with my user I get below error.
```
[W 2021-03-18 05:02:18.675 JupyterHub ldapauthenticator:275] No entry found for user 'testuser' when looking up attribute 'sAMAccountName'
[W 2021-03-18 05:02:18.675 JupyterHub base:713] Failed login for testuser
```
versions
```
python==3.8.5
jupyterhub==1.1.0
jupyterhub-ldapauthenticator==1.3.2
```
Tried different combinations in configuring the attributes but the error remains the same. 
`c.LDAPAuthenticator.lookup_dn_search_user` is the ldap account that I have mentioned. Is it the correct way?
Any suggestions please.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by yash64** [comment]
> Hi 👋 This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

This may not be an issue to change existing content and I highly appreciate the amount of work the team does here. But as far as I have seen there is very minimal support on [http://discourse.jupyter.org/](http://discourse.jupyter.org/) as I have seen questions related to this issue posted in the forum and there are no responses from support team. It would really be beneficial to the users if there is a dedicated team supporting on the issues. Thank you once again.

**Comment by manics** [comment]
@yash64 If there are no answers on the Discourse forum it's usually because we don't have an answer. This is especially the case with specialised plugins like LDAPAuthenticator which require specific domain knowledge. The advantage of the Discourse forum is that it's a central community forum where there's a chance someone else will be able to help.
