### ISSUE TITLE
Please permit @ in the username

### ISSUE THREAD

**Issue by cgrozea** [jupyterhub/ldapauthenticator#196]
### Bug description
For my environment (AD) and config, one could login with the email address, but the character '@' is not allowed in the username.
#### Expected behaviour
being allowed to login by using the username firstname.lastname@internetdomain

#### Actual behaviour
The username is rejected for containing not permitted characters
The check is done here: 
https://github.com/jupyterhub/ldapauthenticator/blob/31d70f8420b3c0ffd96d61164e0921bfe2ae431a/ldapauthenticator/ldapauthenticator.py#L92

### How to reproduce
I guess this is dependent on the AD configuration

### Your personal set up
# jupyterhub_config.py
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      lookup_dn: false
      bind_dn_template:
        - "{username}"
      user_attribute: sAMAccountName

According to OWASP:

There are certain characters that are considered special characters in a DN.

The exhaustive list is the following: \ # + < > , ; " = and leading or trailing spaces.

Some "special" characters that are allowed in Distinguished Names and do not need to be escaped include:

* ( ) . & - _ [ ] ` ~ | @ $ % ^ ? : { } ! '

**Comment by reinierpost** [comment]
You can override the regex in the configuration. E.g., we have this:

```
# accept usernames consisting of digits
c.LDAPAuthenticator.valid_username_regex = r'^[a-z0-9][a-z0-9_-]*$'
```

**Comment by cgrozea** [comment]
Thank you very much, had no idea it is possible. Tried it and it works, thus I close this issue.

**Comment by reinierpost** [comment]
You're welcome! It took me a while to figure it out as well.
