### ISSUE TITLE
pip install not up to date

### ISSUE THREAD

**Issue by yourinoelnelson** [jupyterhub/ldapauthenticator#20]
The pip install does not install the most recent version of the ldapauthenticator, lookup_dn, user_attribute and user_search_base are missing!

**Comment by yuvipanda** [comment]
I'll make a new relase later today!

**Comment by rdewaele** [comment]
As I recently installed this package through pip and did not end up with the version on the Github page, I'm going to assume that this is still on the to-do list? ;-)

What worked for me in the mean time is to just curl/wget the raw version directly from Github right where the pip install put the older version. I think I removed the .pyc version too at some point.

**Comment by yourinoelnelson** [comment]
@rdewaele I ended up doing something really similar since the pip install did not seem to have been updated!

**Comment by yuvipanda** [comment]
I've just made a release. Sorry for the delay!
