### ISSUE TITLE
Z2JH LDAPStartTLSError on login attempts

### ISSUE THREAD

**Issue by maegul** [jupyterhub/ldapauthenticator#201]
Hi and thanks for all your work on the jupyter ecosystem!

Please see [equivalent post over in the discourse forum](https://discourse.jupyter.org/t/ldap-not-working-ldapstarttlserror/11047).

### Bug description

* Any attempted login results in a `500` and the following error in the logs on the `hub` pod: `ldap3.core.exceptions.LDAPStartTLSError: ('wrap socket error: EOF occurred in violation of protocol (_ssl.c:1131)',)`.

#### Expected behaviour

* Login works with the LDAP server without error.  
* Our current setup, using the Z2JH helm chart `v0.9.X` has not had these issues.

#### Actual behaviour

See above

### How to reproduce

1. Use the same openldap chart (see below) with the `LDAPAuthenticator` and try to login

### Your personal set up

* Z2JH on AWS setup, using the latest version of jupyterhub
* LDAP helm release running the `osixia` openldap image.
  * Specifically, the `geek-cookbook/openldap` chart [see ArtifactHub Page](https://artifacthub.io/packages/helm/geek-cookbook/openldap), *which may be running too old a version of the `osixia` image (1.1.10)*
* Tooling is up to date
  * Use `eksctl` to initialise the EKS and cluster (`eksctl version: 0.67.0`)
  * `kubectl version: 1.22.1`
  * `helm version: 3.7.0`

- <details><summary>Configuration</summary>

```python
# config.yaml
proxy:
  https:
    enabled: true
    hosts:
      - DOMAIN
    letsencrypt:
      contactEmail: EMAIL
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      use_ssl: true  # true or false here doesn't appear to alter the behaviour
      server_address: ldap-proto-openldap.default.svc.cluster.local
      bind_dn_template:
        - 'mail={username},o=DELETED,ou=DELETED,dc=DELETED,dc=com'
        - 'mail={username},o=DELETED,ou=DELETED,dc=DELETED,dc=com'
      escape_userdn: true
      lookup_dn: false
      valid_username_regex: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
  defaultUrl: "/lab"
```
</details>

- <details><summary>Logs</summary>

**Full Trace**

*Note that the same error occurs when setup with `https`*

```
[E 2021-09-29 09:52:51.564 JupyterHub web:1789] Uncaught exception POST /hub/login?next=%2Fhub%2F (::ffff:192.168.34.48)
    HTTPServerRequest(protocol='http', host='aac510edbf3624e84a65b2a742db10b8-2112802575.ap-southeast-2.elb.amazonaws.com', method='POST', uri='/hub/login?next=%2Fhub%2F', version='HTTP/1.1', remote_ip='::ffff:192.168.34.48')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/login.py", line 151, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 754, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 469, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 382, in authenticate
        conn = self.get_connection(userdn, password)
      File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 314, in get_connection
        conn = ldap3.Connection(
      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 363, in __init__
        self._do_auto_bind()
      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 391, in _do_auto_bind
        if self.start_tls(read_server_info=False):
      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 1314, in start_tls
        if self.server.tls.start_tls(self) and self.strategy.sync:  # for asynchronous connections _start_tls is run by the strategy
      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/tls.py", line 280, in start_tls
        return self._start_tls(connection)
      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/tls.py", line 289, in _start_tls
        raise start_tls_exception_factory(e)(connection.last_error)
    ldap3.core.exceptions.LDAPStartTLSError: ('wrap socket error: EOF occurred in violation of protocol (_ssl.c:1131)',)
```
</details>

**Comment by zhouyuangan** [comment]
@maegul do you solve this problem?

**Comment by maegul** [comment]
Nope.  From poking around, it seemed to me that Jupyter LDAP support isn't the most solid or reliable thing, which isn't a criticism of Jupyter developers, just an observation supported by some developers themselves, that integrating LDAP is non-trivial and stretches their expertise and time a bit too much.

So instead I'm shifting to using the [Jupyter NativeAuthenticator](https://github.com/jupyterhub/nativeauthenticator), where I've suggested some changes (see [this issue I've raised](https://github.com/jupyterhub/nativeauthenticator/issues/151)) to enable it so serve as a more effective substitute for LDAP.

The NativeAuthenticator basically runs natively on the JupyterHub server itself, so it should have fewer issues going forward, it's definitely easier to modify yourself, and suits a nice small-medium cluster size and simple workflow well.

**Comment by zhouyuangan** [comment]
@maegul I got it, thanks.

**Comment by consideRatio** [comment]
Thanks for a great writeup!!!

Looking at this, trying to figure out details a few years later:
- The latest z2jh at the point of time when this was written was z2jh 1.1.3, which had ldapauthenticator 1.3.2 in it, with ldap3 version 2.9.
- z2jh 0.9.0 had ldapauthenticator 1.3.0 with ldap version 2.7.

This is a SSL/TLS issue, and that has been worked quite a bit recently. I'm not confident this is resolved or not, but I hope to get a new release out and then if this is reproduced once again, we try to resolve it.

I'll go for a close for now, thinking it could already be fixed, or that its about to get fixed soon by a username escaping thing I'll open a PR for soon.
