### ISSUE TITLE
Support of username contains upper case

### ISSUE THREAD

**Issue by abzymeinsjtu** [jupyterhub/ldapauthenticator#202]
### Proposed change

ldapauthenticator doesn't support logging with username which contains uppercase, for JupyterHub perform a username normalization(including a lower function call ) during authentication.

There has been a  [pam_normalize_username](https://github.com/jupyterhub/jupyterhub/issues/2059) option for PAMAuthenticator, with which JupyterHub would check the existence of case insensitive user name instead of a lower action.

Hope that ldapauthenticator will support the feature as well

### (Optional): Suggest a solution

make a full search of given dn to make a match

**Comment by maffinyep** [comment]
@abzymeinsjtu issue still occurrs, why it has been closed? how have you address it?
