### ISSUE TITLE
LDAPAuthenticator with allowed_users

### ISSUE THREAD

**Issue by christineleroy** [jupyterhub/ldapauthenticator#203]
### Bug description
Not using allowed_users. Any authenticated user will be allowed 

#### Expected behaviour
 I would like to configure a whitelist of users authorized to login to the jupyterhub with LDAPAuthenticator 

#### Actual behaviour
All LDAP users can connect to the jupyterhub . 

### How to reproduce
c.LDAPAuthenticator.allowed_users = {'xxxxx'}
c.Authenticator.allowed_users = {'xxxxx'}

### Your personal set up

- OS:ubuntu 18
- pip3 list | grep jupyter
jupyter-client                   6.1.12    
jupyter-core                     4.7.1     
jupyter-packaging                0.10.1    
jupyter-server                   1.6.4     
jupyter-telemetry                0.1.0     
jupyterhub                       1.4.0     
jupyterhub-dummyauthenticator    0.3.1     
jupyterhub-firstuseauthenticator 0.14.1    
jupyterhub-idle-culler           1.1       
jupyterhub-ldapauthenticator     1.3.2     
jupyterhub-nativeauthenticator   0.0.7     
jupyterhub-systemdspawner        0.15.0    
jupyterhub-tmpauthenticator      0.6       
jupyterhub-traefik-proxy         0.1.6     
jupyterlab                       3.0.7     
jupyterlab-pygments              0.1.2     
jupyterlab-server                2.1.4     
the-littlest-jupyterhub          0.1

**Comment by consideRatio** [comment]
Closing in favor of #260
