### ISSUE TITLE
Fetch UIDs from LDAP server

### ISSUE THREAD

**Issue by quasis** [jupyterhub/ldapauthenticator#205]
I'm not sure whether this feature request belongs here, it sort of falls between two (or even 3) chairs.

There is plugin [out there](https://github.com/benhosmer/jupyterhub-ldapcreateusers), that combines between LDAPAuthenticator and LocalAuthenticator. It is a 1 line project, that inherits both authenticators in order to create a local posix user once he was authenticated against some LDAP server. The only problem with this "combined" authenticator, is that **local UIDs are arbitrary** and dont match the UIDs stored on the LDAP server.

Now, LocalAuthenticator has support for UID maps, you can do the following:
```
c.LocalAuthenticator.uids = {'alice': 1000, 'bob': 1001}
```
So theoretically, if LDAPAuthenticator could retrieve the UID of the user and populate `uids` field, with bindDN-UID pair, the problem would be solved.

**Comment by consideRatio** [comment]
Thanks for the clear description! I think I'll go for a close here though. I think reasoning about this may belong in the project working with the local users.
