### ISSUE TITLE
c.LDAPAuthenticator.user_attribute to get userID  instead of UserName

### ISSUE THREAD

**Issue by Gopichandh** [jupyterhub/ldapauthenticator#208]
Hi team,

I'm installing JupyterHUb 2.1.1.version on Openshift Container Platform 

Hub is up and running and able to create NoteBook pods. using c.LDAPAuthenticator.user_attribute = 'sAMAccountName'. I am trying to retrieve UserID but I am getting UserName instead.

Could someone help me to fix get the UserID

Thanks,
Gopichandh

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
