### ISSUE TITLE
openldap config

### ISSUE THREAD

**Issue by RadFromOrange** [jupyterhub/ldapauthenticator#214]
### Bug description

openldap doesn't wotk with official lib but works with the unofficial lib! invalid credentials! 

#### Expected behaviour

connection OK

#### Actual behaviour 

KO! but works with this lib

[jupyterhub-ldap-authenticator](https://github.com/hansohn/jupyterhub-ldap-authenticator) 

### How to reproduce

connect to openldap , searchfilter = (uid={username})

**Comment by manics** [comment]
Hi! Please update the title and description to be more informative, including full information for someone to reproduce your problem. Note there's no need to use ALL CAPS in a title.
