### ISSUE TITLE
incomplete documentation, not working project.

### ISSUE THREAD

**Issue by awesome-crab** [jupyterhub/ldapauthenticator#215]
### Bug description

Hello everyone.
Sorry for the provocative title. But I am now trying that for several days and i am slowly but surely reaching my frustration limit.
It seems not to be possible to use the jupyterhub-ldapauthenticator. If you do it as suggested in the docs it does not work. There is no example to find anywhere. Whenever I search for the issue I only find people who seem to have simillar issues but none of them ever got an answer in their posts. The same for discourse.jupyter.org. I will never sign up to that. For what if you never get help...?
Also from reading all of the ldap issue which I was able to find I think the documentation here was not updated to the latest versions of the code?

Anyways I will describe my issue here.
I have jupyterhub running inside an lxc container on a server in the company network. I want to use ldap active directory authentication. Thats is mainly to reduce the workload of admins. Basically the creation and deletion of users should be avoided this way. Whatever config I have it is not working. I always see 500 internal error in jupyterhub. Depending on the config the error messages in jupyterhub logs change:
- ldap3.core.exceptions.LDAPStartTLSError: startTLS failed - unavailable
- ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 110] Connection timed out
- ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: [Errno 104] Connection reset by peer
- ldap3.core.exceptions.LDAPSocketOpenError: invalid server address

What really leaves me puzzled is that I am able to see the users in ldap using the ldapsearch command inside the lxc container of jupyterhub.
Also it is possible to include a small ldap3 script in the jupyterhub_config.py which is able to access ldap and get all users.
the ldapsearch command and the python ödap3 script use the exact same credetials as specified in the jupyterhub_config.

#### Expected behaviour

I expect ldap to work? I saw the hint that ldap is complicated. but I dont get why ldapsearch and my custom ldap3 script seem to have access to our ldap ad but jupyterhub_ldapauthenticator does not work.

#### Actual behaviour

jupyterhub_ldapauthenticator does not work.
Is there anybody who can say in march 2023 they have jupyterhub with the latest version and working ldap authenticator implementation?

### How to reproduce

try set up the littlest jupyter hub in an ubuntu 20.04 lxc container and implement ldap. If that is working for you please sahre an anonymized version of your tljh-config. Would be highly appreciated.
Also, if there is an ldap expert reading this, feel free to share some wisdom on ldap. What are issues which might exist?

What do you need from me in order to be able to help?

### Specs

ubuntu 20.04
Jupyterhub 1.5.1
ldapauthenticator.ldapauthenticator.LDAPAuthenticator-1.3.2

**Comment by consideRatio** [comment]
Thank you for writing this up, I understand your frustration - this project became stale and had no active maintainers using it for a long time =/ I'm also not an active user, but I felt like investing my time into getting it up to date and functional.

I'll mark this issue to be closed with #258 that doesn't fully handle this issue in a way, but I think #258 and getting #49 to resolve can make things work well again.

**Comment by consideRatio** [comment]
Closing in favor of #259
