### ISSUE TITLE
c.LDAPAuthenticator.allowed_groups now working.

### ISSUE THREAD

**Issue by nicolajthulin** [jupyterhub/ldapauthenticator#240]
### Bug description

c.LDAPAuthenticator.allowed_groups now working.

### How to reproduce

Logout -> Login

#### Expected behaviour

Login succes

#### Actual behaviour

login failed with:

```
[W 2024-08-20 11:51:12.605 JupyterHub ldapauthenticator:454] username:[username] User not in any of the allowed groups
```

### Your personal set up

jupyterhub 5.1.0
jupyterhub-ldapauthenticator 1.3.2

c.LDAPAuthenticator.server_address = 'ad-server'
c.LDAPAuthenticator.use_ssl = True
c.LDAPAuthenticator.server_port = 636
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = 'ad-user'
c.LDAPAuthenticator.lookup_dn_search_password = '*****'
c.LDAPAuthenticator.user_search_base = 'ad-base'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'
c.LDAPAuthenticator.escape_userdn = False
c.LDAPAuthenticator.bind_dn_template = '{username}@company.com'

**Comment by consideRatio** [comment]
One issue is configuring bind_dn_template along with lookip_dn, i've updated the readme example so its no longer configuring that.

**Comment by nicolajthulin** [comment]
Hej again,

I tried this: https://github.com/jupyterhub/ldapauthenticator?tab=readme-ov-file#active-directory-integration

´´´
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = 'ldap_search_user_technical_account'
c.LDAPAuthenticator.lookup_dn_search_password = 'secret'
c.LDAPAuthenticator.user_search_base = 'ou=people,dc=wikimedia,dc=org'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'
´´´

But it doesn't work with "c.LDAPAuthenticator.allowed_groups"
