### ISSUE TITLE
Support `allowed_users` and `admin_users`

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ldapauthenticator#260]
`allowed_user` and `admin_users` are config options from the Authenticator base class. They should work in this authenticator class as well, allowing usernames to be listed in order to be allowed access.

**Comment by consideRatio** [comment]
I think https://github.com/jupyterhub/ldapauthenticator/pull/269 is a step towards making sure that `allowed_user` and `admin_users` works more as expected, where for example users doesn't have to be listed both in a allowed group and individually in allowed_users.

**Comment by minrk** [comment]
#269 actually doesn't fix allowed_users (_yet_) but it's a tiny change to do so

**Comment by minrk** [comment]
This is now fixed and tested by #269
