### ISSUE TITLE
Auth ok, but the users are not added

### ISSUE THREAD

**Issue by kiarn** [jupyterhub/ldapauthenticator#29]
Hello,

Thanks for providing such a module, it is very useful for schools.
As written in the title, I managed to use ldapauthenticator and to log in with ldap credentials, when an unix account already exists on the server who host jupyterhub.
But I get an error 'getpwnam(): name not found: USERNAME' for all new users, and I have to allow all users to login for my school.

I've seen https://github.com/jupyterhub/jupyterhub/issues/466, but I don't want to use the DockerSpawner.

My config : 

```
# pip3 list | grep jup
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.1)
jupyterhub (0.7.1)
jupyterhub-ldapauthenticator (1.1)
```

```
# grep -v '^#' jupyterhub_config.py  | sort -u
c.Authenticator.admin_users = {'admin'}
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.JupyterHub.port = 443
c.JupyterHub.spawner_class = 'jupyterhub.spawner.LocalProcessSpawner'
c.JupyterHub.ssl_cert = 'jupyterhub.crt'
c.JupyterHub.ssl_key = 'jupyterhub.key'
c.LDAPAuthenticator.bind_dn_template = 'uid={username},ou=accounts,dc=domain,dc=com'
c.LDAPAuthenticator.server_address = 'ldap.domain.com'
c.LocalAuthenticator.add_user_cmd = ['useradd', '-m']
c.LocalAuthenticator.create_system_users = True
c.Spawner.notebook_dir = '~'
```

Did I miss something in the config file ?

Thanks for your help

**Comment by willingc** [comment]
Hi @kiarn, It looks as if the functionality that you are looking for (creating users) has not yet been implemented in this authenticator. See discussion here: https://github.com/jupyterhub/jupyterhub/issues/932#issuecomment-271911940

**Comment by dhirschfeld** [comment]
Please see [this](https://github.com/jupyterhub/ldapauthenticator/pull/36#issuecomment-313219910) comment for how to integrate LDAP with PAM.
