### ISSUE TITLE
LDAP Auth doesn't  work -> 500 : Internal Server Error ->     KeyError: 'getpwnam(): name not found: username'

### ISSUE THREAD

**Issue by kamilszkoda** [jupyterhub/ldapauthenticator#30]
It is my config file:

c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = '10.48.1.151'
c.LDAPAuthenticator.use_ssl = False
c.LDAPAuthenticator.bind_dn_template = 'CN={username},OU=Special_Accounts,OU=PL_WAR,OU=mycompany,DC=mycompany,DC=com'
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = 'DC=mycompany,DC=com'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'

**and I receive an error: 500 : Internal Server Error ->     KeyError: 'getpwnam(): name not found: datawizards'. I try to login to JupyterHub with LDAP authentication. User and password verification has been passed properly but I don't understand what is going on next. I suppose application is looking my user "datawizards" on OS level. Why ?. I want to login through LDAP to application without user creation inside Linux.**

**Any idea what is wrong ?**

[I 2017-01-25 10:55:33.209 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[W 2017-01-25 10:55:33.212 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-01-25 10:55:33.212 JupyterHub app:1176] Starting proxy @ http://0.0.0.0:8000/
[D 2017-01-25 10:55:33.213 JupyterHub app:1177] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error', '--log-level', 'debug']
[D 2017-01-25 10:55:33.430 JupyterHub app:1205] Proxy started and appears to be up
[I 2017-01-25 10:55:33.431 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
[I 2017-01-25 10:55:35.750 JupyterHub log:100] 302 GET / (@10.48.2.111) 2.47ms
[I 2017-01-25 10:55:35.825 JupyterHub log:100] 302 GET /hub (@10.48.2.111) 0.42ms
[I 2017-01-25 10:55:35.888 JupyterHub log:100] 302 GET /hub/ (@10.48.2.111) 0.72ms
[I 2017-01-25 10:55:35.958 JupyterHub log:100] 302 GET /login (@10.48.2.111) 0.63ms
[I 2017-01-25 10:55:36.068 JupyterHub log:100] 200 GET /hub/login (@10.48.2.111) 32.31ms
[E 2017-01-25 10:55:41.476 JupyterHub user:251] Unhandled error starting datawizards's server: 'getpwnam(): name not found: datawizards'
[E 2017-01-25 10:55:41.488 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (10.48.2.111)
    HTTPServerRequest(protocol='http', host='10.249.1.6:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='10.48.2.111', headers={'X-Forwarded-Host': '10.249.1.6:8000', 'Cache-Control': 'no-cache', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Port': '8000', 'Host': '10.249.1.6:8000', 'X-Forwarded-For': '10.48.2.111', 'Accept': 'text/html, application/xhtml+xml, image/jxr, */*', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '41', 'Connection': 'close', 'Referer': 'http://10.249.1.6:8000/hub/login', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586', 'X-Forwarded-Proto': 'http', 'Accept-Language': 'en-US,en;q=0.5'})
    Traceback (most recent call last):
      File "/opt/anaconda2/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/anaconda2/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/opt/anaconda2/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/anaconda2/lib/python3.5/site-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/opt/anaconda2/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/anaconda2/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/anaconda2/lib/python3.5/site-packages/jupyterhub/spawner.py", line 778, in start
        env = self.get_env()
      File "/opt/anaconda2/lib/python3.5/site-packages/jupyterhub/spawner.py", line 770, in get_env
        env = self.user_env(env)
      File "/opt/anaconda2/lib/python3.5/site-packages/jupyterhub/spawner.py", line 757, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: datawizards'

**Comment by Myllyenko** [comment]
Did you manage to resolve this? I ran into the same issue and have no idea what to do with it.

**Comment by fjbsantiago** [comment]
Hey @kamilszkoda, did you figure out what was wrong?

**Comment by kamilszkoda** [comment]
Yes. My work mate developed better version of Ldap for this application. Is already merged.
You have to configure parameters from below:

c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
c.LDAPAuthenticator.lookup_dn_search_user = 'ldap_search_user_technical_account'
c.LDAPAuthenticator.lookup_dn_search_password = 'secret'
c.LDAPAuthenticator.user_search_base = 'ou=people,dc=wikimedia,dc=org'
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
c.LDAPAuthenticator.escape_userdn = False

The most import with this error is that free:
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'

You need to know structure of your LDAP and compare.

**Comment by fjbsantiago** [comment]
Thank you for helping. I was not using LDAP. My issue was that I was running jupyterhub and it was trying to find existing users when spawning Notebooks. I changed the configuration to use [Simple Spawner](https://github.com/yuvipanda/jupyterhub-simplespawner) for now while I am just testing it and the error is gone.

**Comment by dhirschfeld** [comment]
> *did you figure out what was wrong?*

> *Yes. My work mate developed better version of Ldap for this application. Is already merged.*

Closing as fixed. If that is not the case please feel free to reopen and we can continue the discussion...
