### ISSUE TITLE
can't specify Tls object or parameters

### ISSUE THREAD

**Issue by roymarantz** [jupyterhub/ldapauthenticator#35]
According to http://ldap3.readthedocs.io/ssltls.html#the-tls-object 

IF you don’t use a specific Tls object and set use_ssl=True in the Server definition, a default Tls object will be used, it has no certificate files, uses the ssl.PROTOCOL_SSLv23 (if available in your Python interpreter) and performs no validation of the server certificate.

I need to specify certificate file and other options.  Am I missing someway to do this?  My python is a not the strongest.

**Comment by dhirschfeld** [comment]
This feature request is being tracked in #49
