### ISSUE TITLE
LDAP Auth doesn't work if an user with the same name doesn't exist on the system

### ISSUE THREAD

**Issue by Erickira3** [jupyterhub/ldapauthenticator#38]
When trying to use LDAP to log user on jupyterhub I get:
File "/usr/local/lib/python3.4/dist-packages/jupyterhub/spawner.py", line 757, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: johny'

The user does exist in the LDAP and the authentication work, when I do:
ldapwhoami -vvv -h localhost -D uid=johny,ou=people,dc=example,dc=com -x -w secret
ldap_initialize( ldap://localhost )
dn:uid=johny,ou=people,dc=example,dc=com
Result: Success (0)

When I create an user on the machine (without the same password but the same username) it does work.
I would like to log user with LDAP information without haign to create myself an account for every user on the machine (they have remote folder that I can mount to store their notebook and files).  Is there any way to achieve something like that?

**Comment by Erickira3** [comment]
Sorry, I managed to make it work in the end using https://github.com/benhosmer/jupyterhub-ldapcreateusers
It create the user on the machine when it can't be found and so fix my problem.

**Comment by VanDavv** [comment]
I can confirm that **jupyterhub-ldapcreateusers** package which @Erickira3 shared works flawlessly
