### ISSUE TITLE
JupyterHub-Livy-Sparkmagic-Kerberos

### ISSUE THREAD

**Issue by venkatchetkuri** [jupyterhub/ldapauthenticator#42]
Here is my use case:
Run spark jobs in JupyterHub notebooks against a Kerborised (YARN/Spark) cluster.
I don't want LDAP users to have Kerberos principals.
I am allowed to create service principals.

What i did so far on a single machine is :

1. Installed Jupyterhub - Success.
https://github.com/jupyterhub/jupyterhub

2. Installed LIvy - Success.
https://github.com/cloudera/livy

3. Added this node as a gateway node to the Cloudera cluster - Success.

4. configured LDAP authenticator -Success.
https://github.com/jupyterhub/ldapauthenticator

5. Sparkmagic - Done
https://github.com/jupyter-incubator/sparkmagic

6. Kerberos Authentication - KDC authenticator - Done
https://github.com/bloomberg/jupyterhub-kdcauthenticator

Error message when I'm trying to run :
#KRB5_CONFIG=/etc/krb5.conf
#KRB5_KTNAME=/opt/livy/jhub.keytab
#jupyterhub --ip=public.ip --port=8000 --no-ssl --config=/opt/jupyterhub_config.py

[C 2017-06-27 21:10:31.135 JupyterHub application:90] Bad config encountered during initialization:
[C 2017-06-27 21:10:31.135 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f03e8070c88> instance must be a type, but 'kdcauthenticator.kdcauthenticator.KDCAuthenticator' could not be imported

Being  a newbie to Jupyter/Spark and Kerberos, I'm not able figure out what I'm missing.

Here I am attaching the overall architecture and the configuration files of livy and jupyterhub.

[jupyterhub_config.txt](https://github.com/jupyterhub/ldapauthenticator/files/1106110/jupyterhub_config.txt)
[livy_conf.txt](https://github.com/jupyterhub/ldapauthenticator/files/1106109/livy_conf.txt)
<img width="994" alt="screen shot 2017-06-26 at 9 20 16 pm" src="https://user-images.githubusercontent.com/25988196/27599010-1e3cbe72-5b1c-11e7-803f-d4f2f0da41d1.png">

Here I am attaching the overall architecture and the configuration files of livy and jupyterhub.

**Comment by venkatchetkuri** [comment]
Quick update:
Installed KDCAuthenticator plugin and applied changes to the JupyterHub configuration file.
Getting `405 : Method Not Allowed` message upon user's login.
Spent quite a lot time to troubleshoot the issue but, no luck.

**Comment by dhirschfeld** [comment]
This looks to be an issue with the `KDCAuthenticater` in which case you should instead ask for help on that repo - https://github.com/bloomberg/jupyterhub-kdcauthenticator

I'm closing this issue as I don't think it's related to `LDAPAuthenticator`. If you think this is incorrect please feel free to reopen and we can continue the discussion...

*Note:* For anyone to help you'll probably have to specify both the `jupyterhub_config.py` you're using as well as more context in the output logs.
