### ISSUE TITLE
Without bind_dn_template, any password is authenticated successfully!

### ISSUE THREAD

**Issue by djrobstep** [jupyterhub/ldapauthenticator#44]
When initially configuring ldapauthenticator, I accidentally left bind_dn_template out of my config. When I tested it, I noticed it was authenticating me even with incorrect passwords!

This seems very dangerous. Although this parameter is required, authentication should probably always fail rather than always succeeding (or jupyter hub should simply refuse to start if required values are missing).

This happened when I had the following config vars set: `server_address, lookup_dn, user_search_base, user_attribute`.

**Comment by dhirschfeld** [comment]
This sounds like a bug. I'll check if I can reproduce to confirm...

**Comment by ermakovpetr** [comment]
this is fact!
after update 1.1->1.2.2 have this problem

**Comment by ermakovpetr** [comment]
If don't set `bind_dn_template` - `bind_dn_template=[]`
and `isBound` don't set True
https://github.com/jupyterhub/ldapauthenticator/blob/master/ldapauthenticator/ldapauthenticator.py#L315-L335

**Comment by ermakovpetr** [comment]
But we can take `userdn` from connection after search user `conn.response[0]['dn']`
my temporarily dirty fix : 
https://github.com/jupyterhub/ldapauthenticator/pull/88
If you ok about the idea, I try to make pull-request correctly and beautifully

**Comment by AnirudhVyas** [comment]
How do we set bind_dn_template?

**Comment by dhirschfeld** [comment]
@AnirudhVyas - `bind_dn_template` is set in your `jupyterhub_config.py` file.
https://github.com/jupyterhub/ldapauthenticator#ldapauthenticatorbind_dn_template

**Comment by dhirschfeld** [comment]
I can't reproduce and I can't follow the logic how this could be the case.

`isBound` is initially set to `False`:
https://github.com/jupyterhub/ldapauthenticator/blob/718eb59c91f5aa754a598cf12afe292a81dd644c/ldapauthenticator/ldapauthenticator.py#L298

If `bind_dn_template` is empty this entire block is skipped:
https://github.com/jupyterhub/ldapauthenticator/blob/718eb59c91f5aa754a598cf12afe292a81dd644c/ldapauthenticator/ldapauthenticator.py#L315

therefore `isBound` is still `False` here and this block is also skipped:
https://github.com/jupyterhub/ldapauthenticator/blob/718eb59c91f5aa754a598cf12afe292a81dd644c/ldapauthenticator/ldapauthenticator.py#L337

which then falls through to the `else` clause which blocks access:
https://github.com/jupyterhub/ldapauthenticator/blob/718eb59c91f5aa754a598cf12afe292a81dd644c/ldapauthenticator/ldapauthenticator.py#L377-L381

**Comment by dhirschfeld** [comment]
Poking around some more, it seems that if your `bind_dn_template` is an empty string `''` then it does indeed authenticate any password :(

**Comment by ermakovpetr** [comment]
@dhirschfeld 
correctly I understand that my PR (https://github.com/jupyterhub/ldapauthenticator/pull/88) doesn't conflict your PR. and I can add functionality (get `bind_dn_template` from first request's response)

**Comment by dhirschfeld** [comment]
@ermakovpetr - yes, I think the functionality in #88 is orthogonal to that in #95
