### ISSUE TITLE
Add a MANIFEST.in file

### ISSUE THREAD

**Issue by willingc** [jupyterhub/ldapauthenticator#50]
Based on input from @Carreau from today's team meeting, let's consider adding.

**Comment by dhirschfeld** [comment]
Python packaging best practices seem to be evolving too quickly for me to keep up! Do you have any link to describe how this should be used / what problems it solves?

**Comment by willingc** [comment]
Hi @dhirschfeld,

This is part of discussion that prompted this issue (https://github.com/jupyter/nbconvert/issues/667).

I don't think it is strictly necessary to add a MANIFEST.in file these days unless one is adding non-code files or files outside of the basic Python file tree.

This is the most current resource that I know for all things packaging: https://packaging.python.org

One place that you may wish to look at are the additional fields in setup.py for metadata to be displayed by pypi.org. For this project, it looks like https://pypi.org/project/jupyterhub-ldapauthenticator/
