### ISSUE TITLE
package on pypi.org outdated

### ISSUE THREAD

**Issue by bbrauns** [jupyterhub/ldapauthenticator#57]
Hi, the installation guide recommends installing this package via:
 `pip install jupyterhub-ldapauthenticator`
but https://pypi.python.org/pypi/jupyterhub-ldapauthenticator shows that the git repo of another user with a rather old version is used: https://github.com/yuvipanda/ldapauthenticator

How do I get the current HEAD of master into my jupyterhub?

**Comment by dhirschfeld** [comment]
This will be fixed by #70
