### ISSUE TITLE
Comma not escaped in username

### ISSUE THREAD

**Issue by cr42** [jupyterhub/ldapauthenticator#63]
I'm using Active Directory LDAP with following attributes:
dn: `CN=Doe\, John,CN=Users,DC=mycompany,DC=com`
cn: `Doe, John`

My configuration is the following:
`c.LDAPAuthenticator.allowed_groups = ['CN={username},CN=Users,DC=mycompany,DC=com'`
`c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'cn'`

It seems the authentication fails since the comma in the cn is not escaped [which is required for AD](https://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx) and therefore doesn't match the dn. I get the following reported in the log:
```
[D 2018-03-02 20:47:41.249 JupyterHub ldapauthenticator:278] Attempting to bind jdoe with CN=Doe, John,CN=Users,DC=mycompany,DC=com
[D 2018-03-02 20:47:41.272 JupyterHub ldapauthenticator:328] Status of user bind jdoe with CN=Doe, John,CN=Users,DC=mycompany,DC=com : False
    LDAPBindError: automatic bind not successful - invalidCredentials
[
```

My guess is the escape_userdn_if_needed() function needs to handle this case since the ldap3 escape_filter_chars does not escape the comma.

```
def escape_userdn_if_needed(self, userdn):
        if self.escape_userdn:
            return escape_filter_chars(userdn)
        else:
            return userdn
```

If there's a way around this problem by simply changing the configuration please let me know.

**Comment by dhirschfeld** [comment]
Fixed by #63
