### ISSUE TITLE
lookup_dn_search_user not recognized by 'LDAPAuthenticator'

### ISSUE THREAD

**Issue by whitebluecloud** [jupyterhub/ldapauthenticator#69]
hi, i`m trying to bind this module but i`m failed.
How do I resolve this issue?
Please forgive me for not being able to write english very well..

JupyterHub configurable:168] Config option `lookup_dn_search_user` not recognized by `LDAPAuthenticator`.  Did you mean `lookup_dn`?
JupyterHub configurable:168] Config option `lookup_dn_search_password` not recognized by `LDAPAuthenticator`.

**Comment by consideRatio** [comment]
Sounds like you have a jupyterhub config file (`jupyterhub_config.py`) that specifies `lookup_dn_search_user` somewhere. Could you provide that config file?

For more information about config files, see
https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/getting-started/config-basics.md

**Comment by dhirschfeld** [comment]
I believe this functionality hasn't made it into a released version so you'd have to run from master. Using pip you can install the current master with:
```
pip install git+https://github.com/jupyterhub/ldapauthenticator.git
```
This will require you to have git installed

**Comment by whitebluecloud** [comment]
@consideRatio  @dhirschfeld Thanks for your help.

I deleted all the modules I had installed and reinstalled them using anaconda. As a result, it succeeded in certification. Probably, some modules installed with a pip are incompatible.
thanks.

**Comment by dhirschfeld** [comment]
Since it's working for you now I'll go ahead and close this issue. Feel free to reopen or open a new issue if you run into any further problems...
