### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/ldapauthenticator#70]
It's probably about due and would stop the steady trickle of people confused that the examples in the README don't work because the functionality has never been released.

***Plan of attack:***
- [x] Triage issues
- [x] Tag 1.2
- [x] Release to PyPI
- [x] Create conda-forge recipe

**Comment by yuvipanda** [comment]
Hey @dhirschfeld! I unfortunately haven't had much time to deal with maintenance here, and likely won't in the future. Me (and the JupyterHub team!) would appreciate help with maintaining this authenticator. Would you consider helping us out with maintenance? I'd be happy to give you merge rights here and access to the PyPI package. What do you think?

**Comment by dhirschfeld** [comment]
I'd be happy to help and was in fact just looking around to see what the release process is!

**Comment by dhirschfeld** [comment]
I just created an account on PyPI with the username `dhirschfeld`

**Comment by dhirschfeld** [comment]
Thanks! I'll see what I can do to help out on the maintenance/admin side...

**Comment by dhirschfeld** [comment]
Right, done and dusted! Version 1.2.0 is available on pypi, and shortly conda-forge.

Hopefully there are no problems but if there are I'll just fix them and make a quick patch release...

**Comment by choldgraf** [comment]
way to go @dhirschfeld !!! thanks for the help :-)
