### ISSUE TITLE
Feature Request: support admin_users query

### ISSUE THREAD

**Issue by JoeJasinski** [jupyterhub/ldapauthenticator#72]
Hi all, 

It would be great if this authenticator could support an LDAP query that would designate admin_users and update that list dynamically (not require a restart). Since ldapauthenticator already has all of the machinery to access LDAP, it seems like it might be a good place to optionally populate the admin_users set based on an LDAP query. Thanks for reading.

**Comment by dhirschfeld** [comment]
That sounds sensible though whether or not it requires a restart is probably up to JupyterHub

**Comment by timhughes** [comment]
Also having `c.LDAPAuthenticator.admin_groups` which accepts a list similar in implementation to `c.LDAPAuthenticator.allowed_groups`

**Comment by mk-raven** [comment]
Any updates of this issue?
5 years have passed..

**Comment by consideRatio** [comment]
Closing this in favor of #260. I'm reducing this to listing users to not change the typical behavior of `Authenticator.admin_users` though, but `admin_groups` or similar could be implemented to get admin users if they are part of an admin group. This is tracked by https://github.com/jupyterhub/ldapauthenticator/issues/239
