### ISSUE TITLE
LDAPAuthenticator w/zero to jh on K8s

### ISSUE THREAD

**Issue by roversne** [jupyterhub/ldapauthenticator#80]
Hi everyone!

Been trying to get this tested working but with little success. Finding depending on a variety of configurations (mostly those I have found that DO work in other JH deployments) end up with the same results - failed container deployment with either of the two outputs:

ModuleNotFoundError: No module named 'ldapauthenticator'

or

The 'authenticator_class' trait of &lt;jupyterhub.app.JupyterHub object at 0x7fd65c760f60&gt; instance must be a type, but 'ldapauthenticator.LDAPAuthenticator' could not be imported

I am deploying with the v6 HELM chart, but have tried with 04, and 050 as well.

When I exec the container I can see that the package is deployed to the container (jupyterhub-ldapauthenticator==1.2.1)

Ive tried to pair the config down to just the instantiation of the adapter, the ldap server, and the template to try and get even the base config to load but with no luck.

I am supplying the config params via the config yaml in the hub extraconfig section. I am wondering if I have an issue in there with not having the right pathing/logic.

Has anyone gotten this to work with the zero-to-jp deployment path?

Thanks!!

**Comment by dhirschfeld** [comment]
Hi @roversne, 
I don't think this is a problem with `ldapauthenticator` but is instead a configuration issue with `zero-to-jupyterhub-k8s`. Unfortunately that is not my area of expertise and you're unlikely to get much help for your problem on this repo so I would recommend opening an issue under https://github.com/jupyterhub/zero-to-jupyterhub-k8s

FWIW the error message clearly states that `ldapauthenticator` *isn't* installed so I'd look to how you're installing it and how you're verifying that it's installed for the source of the problem.
