### ISSUE TITLE
Support for python version 2.7

### ISSUE THREAD

**Issue by vishnuravi3186** [jupyterhub/ldapauthenticator#81]
Hi,

I have installed python 2.7.15 using conda in a linux server , when i try to utilize ldapauthenticator for multi user authentication  I am facing following issue , just want to understand Is there a workaround or support for python 2.7

Python version - Python 2.7.15 :: Anaconda, Inc.

Error log:

 pip install jupyterhub-ldapauthenticator
Collecting jupyterhub-ldapauthenticator
  Using cached https://files.pythonhosted.org/packages/18/57/eb25276959fd6fee6c48547255cb3f8efb3ced0520474ef5f6eb4ae46b74/jupyterhub-ldapauthenticator-1.2.1.tar.gz
Collecting jupyterhub (from jupyterhub-ldapauthenticator)
  Using cached https://files.pythonhosted.org/packages/be/63/b6967b050e304fe50f21b0e4c587660d150877a9861c7e62b3c7fad31f7b/jupyterhub-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: JupyterHub requires Python version 3.3 or above.

Thanks

**Comment by dhirschfeld** [comment]
JupyterHub requires Python >=3.5 and as a component of JupyterHub `ldapauthenticator` therefore also requires Python >=3.5.

There's no reason to run JupyterHub under py27 as the notebook environments it spawns can still be py27 even though JupyterHub itself is running under py3
