### ISSUE TITLE
I cannot authenticate with this plugin. Is there any error of my LDAP config?

### ISSUE THREAD

**Issue by fishfree** [jupyterhub/ldapauthenticator#86]
JupyterHub and this plugin are both the recent stable version.

```
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = '***.***.***.***'
c.LDAPAuthenticator.bind_dn_template = ['uid={username},app=100000,cn=apps,dc=***.***.***']
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_user = 'uid=admin, cn=users, dc=***.***.***'
c.LDAPAuthenticator.lookup_dn_search_password = '********'
c.LDAPAuthenticator.user_search_base = 'app=100000,cn=apps,dc=***.***.***'
c.LDAPAuthenticator.user_attribute = 'uid'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'uid'
```

**Comment by dhirschfeld** [comment]
What output do you see in the logs?

**Comment by fishfree** [comment]
@dhirschfeld Could you tell me where the log file is, please?

**Comment by dhirschfeld** [comment]
It's the output from the `jupyterhub` process - i.e. if you run:
```
jupyterhub --port=80 --debug
```
...the output from that command will also show debug information from your authenticator class

**Comment by fishfree** [comment]
The log says: PAM Authentication failed (1993@::ffff:10.2.8.19): [PAM Error 3] Error in service module
1993 is the LDAP uid.
Thank you!

**Comment by dhirschfeld** [comment]
Sorry, I'm on Windows (and not an LDAP expert) so that doesn't mean much to me.

I'd suggest re-posting the logs with a lot more context (i.e. the entire log output, not just one line) and hopefully an expert / linux user may be able to see what's wrong.

**Comment by tedstrauss** [comment]
When you start jupyterhub on the command line, include the `--debug` option and you will get logs appearing in the terminal.

**Comment by fishfree** [comment]
@tedstrauss I run the command: jupyterhub --port=80 --debug, and when I logged with a LDAP user, it says:
The log says: PAM Authentication failed (1993@::ffff:10.2.8.19): [PAM Error 3] Error in service module
1993 is the LDAP uid.

**Comment by annyip** [comment]
any resolution to this issue?

**Comment by consideRatio** [comment]
Hey! I'm triaging issues in this repo and have for some reason decided to close this issue. Maybe it was too outdated to consider at this point in time for example. Let me know if you think it still captures something of relevance to be tracked still.
