### ISSUE TITLE
"startTLS failed - unavailable" thrown when specifying bind_dn_template

### ISSUE THREAD

**Issue by at-cchaloux** [jupyterhub/ldapauthenticator#89]
When I leave it blank [] I get invalid password for user thrown.

When I specify the bind_dn_template, "startTLS failed - unavailable" is thrown.

This is an attempt to authenticate against AWS AD server (not Simple).

Here is my config:

    c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
    c.LDAPAuthenticator.bind_dn_template = ['CN={username},OU=Users,OU=XXXX,DC=XXXX,DC=XXXX,DC=com']
    c.LDAPAuthenticator.server_address = 'XXX.XXX.XXX.XXX'
    c.LDAPAuthenticator.lookup_dn = True
    c.LDAPAuthenticator.lookup_dn_search_user = 'CN=svcanalytics,OU=svcids,OU=XXXX,DC=XXXX,DC=XXXX,DC=com'
    c.LDAPAuthenticator.lookup_dn_search_password = 'XXXX'
    c.LDAPAuthenticator.lookup_dn_search_filter = '({login_attr}={login})'
    c.LDAPAuthenticator.user_search_base = 'OU=Users,OU=XXXX,DC=XXXX,DC=XXXX,DC=com'
    c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
    c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'CN'
    c.LDAPAuthenticator.escape_userdn = False
    c.LDAPAuthenticator.ldap_tls = 0
    c.LDAPAuthenticator.valid_username_regex = '^[a-zA-Z][.a-z0-9_-]*$'

From what I can tell I am reaching the AD server. There is no SSL here yet and I assume that is why it is defaulting to TLS.

Any ideas?
 Thank you!

**Comment by mannevijayakrishna** [comment]
can someone please help with AD integration issue with Jupiter kind of issue #115 #115 (comment)

**Comment by consideRatio** [comment]
Hey! I'm triaging issues in this repo and have for some reason decided to close this issue. Maybe it was too outdated to consider at this point in time for example. Let me know if you think it still captures something of relevance to be tracked still.
