### ISSUE TITLE
Invalid password after upgrade to jupyterhub_0.9.0

### ISSUE THREAD

**Issue by SofianeB** [jupyterhub/ldapauthenticator#90]
Hi, 

upgraded to 0.9.0 from 0.8.1. 
I had also to upgrade python from 3.4.0 to 3.5.0 (required by 0.9.0) and installed  jupyterhub-ldapauthenticator with pip3.5. 

Now authentication is not working. 

I tried to delete cookies but same error. INVALID PASSWORD. 

Thanks.

**Comment by dhirschfeld** [comment]
Hi @SofianeB,
Can you please post the output of your jupyterhub logs (from the terminal where you ran jupyterhub)?

Also, if you run jupyterhub with the `--debug` switch we should get more information which will help in debugging.

**Comment by SofianeB** [comment]
```
[D 2018-07-02 13:33:00.122 JupyterHub ldapauthenticator:299] TYPE= 'False'
[D 2018-07-02 13:33:00.123 JupyterHub ldapauthenticator:278] Attempting to bind k204213 with uid=k204213,ou=people,o=ldap,o=root
[D 2018-07-02 13:33:00.134 JupyterHub ldapauthenticator:333] Status of user bind k204213 with uid=k204213,ou=people,o=ldap,o=root : False
    LDAPBindError: automatic bind not successful - unavailable
[W 2018-07-02 13:33:00.134 JupyterHub ldapauthenticator:379] Invalid password for user k204213
[W 2018-07-02 13:33:00.135 JupyterHub base:503] Failed login for k204213
[I 2018-07-02 13:33:00.139 JupyterHub log:158] 200 POST /jupyter/hub/login?next= (@127.0.0.1) 19.37ms
```

**Comment by dhirschfeld** [comment]
The `unavailable` is suspicious, but otherwise I couldn't say. I'll have a think on it but in the interim could you post your config here as well so we can check those? I have to go now, but it might help if someone picks this up in the meantime.

**Comment by SofianeB** [comment]
The thing is, if I switch back to previous jupyterhub version (0.8.1), it works normally!

**Comment by dhirschfeld** [comment]
> *it works normally regardless of the configuration.*

That's not actually true - there are an infinite number of ways you could misconfigure `ldapauthenticator` such that it wouldn't work on 0.8.1.

If you're happy sticking with 0.8.1, great you can go ahead and close this issue. If on the other hand you'd like to get it working with 0.9.0 you'll have to provide the requested information for anyone to be able to help you.

**Comment by SofianeB** [comment]
@dhirschfeld just an update. 
The issue is due to the version of jupyterhub-ldapauthenticator. 
I just downgraded to previous release and it works on both jupyterhub versions (0.8.1 and 0.9.0) so that was not a configuration problem.

**Comment by dhirschfeld** [comment]
That your old configuration works with the old version of ldapauthenticator is unsurprising and doesn't eliminate the possibility that your old configuration may need to be updated to use the new version.

**Comment by mfriedemann** [comment]
As dhirschfeld pointed out, trying to second guess possible reasons isn't a very useful approach.

To make it easier for you, SofianeB, you can directly check which changes have actually been implemented between the version that works and the latest one.
Assuming that the working version is 1.2.1 and latest means 1.2.2, you can see the changes [here](https://github.com/jupyterhub/ldapauthenticator/compare/1.2.1...1.2.2).

There is really only one change in the escaping of commas in the resolved username, which is now behind two additional checks
You should compare these newly introduced checks there against your configuration to see if they apply and if that might cause your issue.

HTH,
M.

**Comment by consideRatio** [comment]
Hey! I'm triaging issues in this repo and have for some reason decided to close this issue. Maybe it was too outdated to consider at this point in time for example. Let me know if you think it still captures something of relevance to be tracked still.
