### ISSUE TITLE
Change home URL in setup.py.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/ldapauthenticator#91]
See:

* https://github.com/jupyterhub/ldapauthenticator/blob/master/setup.py#L15

Has:

```
url='https://github.com/yuvipanda/ldapauthenticator',
```

Should be change to this repo now that this repo seems to be the original master copy.

This URL appears as homepage link on PyPi.

**Comment by dhirschfeld** [comment]
Does that automatically flow through to PyPI?

In any case that should probably be changed - care to put in a PR?

**Comment by dhirschfeld** [comment]
It's the sort of thing I'd just use the GitHub web interface to do...

**Comment by GrahamDumpleton** [comment]
PyPi will be updated automatically when next release is made as it pulls that meta data from the package.

Haven't had a chance to do a PR. Quickly created issue before I forgot. Noticed yesterday when answering question on Gitter channel for JupyterHub. Left a message for @yuvipanda on Gitter but wasn't sure if seen, so issue it was until had time.
