### ISSUE TITLE
error trying to configure JupyterHub to allow AD groups

### ISSUE THREAD

**Issue by spitfire2017** [jupyterhub/ldapauthenticator#96]
It keeps saying can't connect to LDAP. Hoping someone can help. Thanks in advance.

[W 2018-08-02 16:32:41.666 JupyterHub ldapauthenticator:230] Can't connect to LDAP
[W 2018-08-02 16:32:41.666 JupyterHub base:351] Failed login for john.do

Following is the config inside JupyterHub_config.py

c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = str("123.123.123.123")
c.LDAPAuthenticator.server_port = 389
c.LDAPAuthenticator.user_attribute = 'sAMAccountName'
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.user_search_base = str(["ou=People,dc=example,dc=com"])
c.LDAPAuthenticator.lookup_dn_search_user = 'john'
c.LDAPAuthenticator.lookup_dn_search_password = 'john'
#c.LDAPAuthenticator.bind_dn_template = []
c.LDAPAuthenticator.allowed_groups = ["CN=jupyter,OU=Groups,DC=example,DC=com"]

**Comment by sqqqrly** [comment]
You can try reaching AD from within the hub pod:
```
# apt install -y curl
# curl --silent "ldap://example.com/dc=example,dc=com??sub?(uid=someone)" | LC_ALL=C tr -cd '\11\12\15\40-\176' || echo "fail"
```
The pipe to `tr` will remove binary that cannot be written to stdout. Some bytes will screw up your terminal.  Our AD serves up jpegs.

**Comment by consideRatio** [comment]
Hey! I'm triaging issues in this repo and have for some reason decided to close this issue. Maybe it was too outdated to consider at this point in time for example. Let me know if you think it still captures something of relevance to be tracked still.
