### ISSUE TITLE
How do I limit certain AD groups to log in to JupyterHub

### ISSUE THREAD

**Issue by spitfire2017** [jupyterhub/ldapauthenticator#97]
Hi,

I have JupyterHub setup and running, the Centos 7 is joined to Windows Domain. right now everyone on the AD is able to log in to JupyterHub. How do I limit logins to certain AD groups? Can I use jupyterhub.auth.PAMAuthenticator ? or do I have to use ldapauthenticator.LDAPAuthenticator?

**Comment by dhirschfeld** [comment]
In `LDAPAuthenticator` you can configure [`allowed_groups`](https://github.com/jupyterhub/ldapauthenticator#ldapauthenticatorallowed_groups)

**Comment by dhirschfeld** [comment]
Closing as answered
